FROM node:16-alpine

WORKDIR /usr/src/app

# install app dependencies
COPY package*.json ./
COPY yarn.lock ./
RUN yarn install --immutable --immutable-cache --check-cache
RUN yarn global add nodemon

CMD ["yarn start"]
