FROM node:16-alpine

WORKDIR /usr/src/app

# install app dependencies
COPY package*.json ./
COPY yarn.lock ./
COPY . .
RUN yarn install --immutable --immutable-cache --check-cache --network-timeout 1000000
RUN yarn global add nodemon

# start app
CMD ["yarn", "start"]
