name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: square-booking-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Login to Docker hub registry
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Test env
        run: |
          echo Location Id:
          echo '${{ secrets.SQUARE_LOCATION_ID }}'
      - name: Build Docker container
        run: |
          echo --- Building docker container 
          docker build -t kmalexandre/square-booking-api:latest -f ./docker/Dockerfile.production .
          docker push kmalexandre/square-booking-api:latest
